### ISSUE TITLE
Implementation using only RGB images and Openpose Keypoints

### ISSUE THREAD

**Issue by nshreyasvi** [nh236/smplify-kids#2]
Hello, Thank you so much for the amazing implementation for the use case of kids. I wanted to know if it might be possible to generate SMPL meshes using just RGB images and Openpose keypoints similar to smplify-x using this library?

**Comment by nh236** [comment]
Hi,
this would require quite some changes, since this repo is focused on RGB-D data.

However, the official SMPLX repo already supports a "kid" functionality. When initializing the model, you have to set `age='kid'` and provide the `kid_template_path` (=filename of the infant mesh) (see [here](https://github.com/vchoutas/smplx/blob/main/smplx/body_models.py#L910)). This will add a shape component that interpolates between the standard model template and the one provided in the kid_template_path.

Using this in the standard SMPLify-X code ([here](https://github.com/vchoutas/smplify-x/blob/master/smplifyx/main.py#L102)) should give you the requested functionality.

The difference between their implementation and ours is that they treat the scale/interpolation parameter like a regular shape parameter, while we optimize for it separately.
